# Generated by Django 5.0.6 on 2024-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_description_en_task_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
